const actions = {
  GET_COUNTER: 'GET_COUNTER',
  GET_COUNTER_SUCCESS: 'GET_COUNTER_SUCCESS',
  GET_COUNTER_FAILURE: 'GET_COUNTER_FAILURE',
  UPDATE_COUNTER: 'UPDAT_COUNTER',
  UPDATE_COUNTER_SUCCESS: 'UPDATE_COUNTER_SUCCESS',
  UPDATE_COUNTER_FAILURE: 'UPDATE_COUNTER_FAILURE'

}

export default actions;
